package:
  name: dasel
  version: 3.3.1
  epoch: 0
  description: "Query and modify data structures using selector strings"
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/TomWright/dasel/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 0d83ee2235b2698ae84402cc03f0e3880a7b8e132408d5b45d02d544da894abc

  - uses: patch
    with:
      patches: CVE-2026-33320.patch

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/dasel
      output: dasel
      ldflags: -s -w -X github.com/tomwright/dasel/v3/internal.Version=v${{package.version}}

test:
  environment:
    contents:
      repositories:
        - /work/packages
        - https://packages.wolfi.dev/os
      keyring:
        - /work/keys/melange.rsa.pub
        - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      packages:
        - busybox
  pipeline:
    - runs: |
        dasel version | grep -q "v${{package.version}}"
        echo '{"name":"dasel","version":3}' | dasel -i json 'name' | grep -q "dasel"
        echo '{"items":[1,2,3]}' | dasel -i json 'items.[1]' | grep -q "2"
