services:
  melange:
    image: cgr.dev/chainguard/melange:latest
    privileged: true
    working_dir: /work
    volumes:
      - .:/work

  apko:
    image: cgr.dev/chainguard/apko:latest
    working_dir: /work
    volumes:
      - .:/work
